### ISSUE TITLE
Running the test case stops after the first failed expectation

### ISSUE THREAD

**Issue by mik01aj** [litixsoft/karma-mocha-reporter#24]
I believe it shouldn't.

This is my example test case:

        it('should show all failures for this silly test', function () {
            expect(1).toBe(0);
            expect(2).toBe(0);
            expect(3).toBe(0);
            expect(4).toBe(0);
        });

Result using `karma-mocha-reporter`:

```
(...)
SUMMARY:
✔ 42 tests completed
✖ 1 tests failed

FAILED TESTS:
  my test suite
    something
      ✖ should show all failures for this silly test
        PhantomJS 1.9.8 (Mac OS X)
      Expected 1 to be 0.
          at src/__tests__/schemaUtils-test.js:126:0
```

Compare this with the output from default `karma`reporter:

```
PhantomJS 1.9.8 (Mac OS X) my test suite something should show all failures for this silly test FAILED
	Expected 1 to be 0.
	    at src/__tests__/schemaUtils-test.js:126:0
	Expected 2 to be 0.
	    at src/__tests__/schemaUtils-test.js:127:0
	Expected 3 to be 0.
	    at src/__tests__/schemaUtils-test.js:128:0
	Expected 4 to be 0.
	    at src/__tests__/schemaUtils-test.js:129:0
PhantomJS 1.9.8 (Mac OS X): Executed 43 of 43 (1 FAILED) (0.336 secs / 0.036 secs)
```

**Comment by 4kochi** [comment]
Ok, seems like a bug.
